//<!--
// Copyright  (c) 2016-2017, Hortonworks Inc.  All rights reserved.
//
// Except as expressly permitted in a written agreement between you or your
// company and Hortonworks, Inc. or an authorized affiliate or partner
// thereof, any use, reproduction, modification, redistribution, sharing,
// lending or other exploitation of all or any part of the contents of this
// software is strictly prohibited.
//-->

= Beacon REST API


Beacon replication engine defines cluster and replication policy entities to maintain information about clusters and policies involved in replication.
The cluster entities are persisted on File system as yml files and Policy entities are persisted into configured database.
It also has in-memory lookup of cluster entities for faster access.

*Cluster definition:*

* *description:* Description of the cluster <optional>
* *fsEndpoint:* HDFS end point <mandatory>
* *beaconEndpoint:* Beacon service endpoint <mandatory>
* *hsEndpoint:* Hive server2 end point <mandatory for Hive replication>
* *local:* flag for annotating local cluster. <optional, default: false>
* *tags:* Cluster tags <Optional. <key, value> pairs>

*Note:* Custom properties can be passed as <key, value> pairs. E.g. dfs.namenode.kerberos.principal=hdfs/_HOST@YOUR-REALM.COM

*Replication policy definition:*

* *type:* {FS|HIVE|HBASE} <mandatory>
* *description:* Description of the policy <optional>
* *sourceDataset:* {FS path | Hive DB } <mandatory>
* *sourceCluster:* Replication source cluster name <mandatory>
* *targetCluster:* Replication target cluster name <mandatory>
* *startTime:* Replication job start time. Date passed should be in the format "yyyy-MM-dd'T'HH:mm:ss" and UTC timezone <Optional>
* *endTime:* Replication job end time. Date passed should be in the format "yyyy-MM-dd'T'HH:mm:ss" and UTC timezone <Optional>
* *frequencyInSec:* Frequency of replication job in seconds <mandatory>
* *tags:* Tags of replication job <Optional. <key, value> pairs>
* *retryDelayInSec:* Delay after which job should be retries in case of failure in seconds <Optional>. Default value is 1800s.
* *retryAttempts:* Number of retry attempts <Optional>. Default value is 3.

Supported Replication types with properties:

*FS Replication*

    * frequencyInSec : Frequency of job run
    * type : Type of replication policy
    * startTime : Job start time (optional)
    * endTime : Job end time (optional)
    * sourceNN : Source cluster Namenode
    * sourceDataset : Location of source snapshot path
    * targetNN : Target cluster Namenode
    * targetDataset : Location of target dataset
    * retryAttempts : Retry count (optional)
    * retryDelay : Retry delay  (optional)
    * queueName : Queue name  (optional)

    * distcpMaxMaps : Maximum number of maps used during distcp (optional)
    * distcpMapBandwidth : Bandwidth in MB/s used by each mapper during replication (optional)
    * tdeEncryptionEnabled : Enable TDE encryption (true|false) (optional)

    * sourceSnapshotRetentionAgeLimit : Delete source snapshots older than this age (optional)
    * sourceSnapshotRetentionNumber : Number of latest source snapshots to retain on source (optional)
    * targetSnapshotRetentionAgeLimit : Delete target snapshots older than this age (optional)
    * targetSnapshotRetentionNumber : Number of latest target snapshots to retain on source (optional)

For FS replication type where it is HDFS <-> HDFS replication, Beacon supports following DistCP options which are optional and can be passed in the custom properties.
Allowed values for these are true or false.

* overwrite [Can take values true or false]

* ignoreErrors

* skipChecksum
* removeDeletedFiles
* preserveBlockSize
* preserveReplicationNumber
* preservePermission
* preserveUser
* preserveGroup
* preserveChecksumType
* preserveAcl
* preserveXattr
* preserveTimes

For more details about DistCP options refer https://hadoop.apache.org/docs/r1.2.1/distcp2.html[_DistCP V2 guide_]. E.g:

removeDeletedFiles=true +
preserveUser=true +
preserveGroup=true +

For HDFS <-> HCFS refer https://docs.google.com/document/d/1PoXt2yOiZXP6IK8FNdX9eEdfZznHxfY01ebGnIYw_ro/edit#[_Beacon HCFS behavior_] document.


*Hive Replication*

   * frequencyInSec : Frequency of job run
   * type : Type of replication policy
   * startTime : Job start time (optional)
   * endTime : Job end time (optional)
   * sourceNN : Source cluster Namenode (optional)
   * sourceHiveServer2Uri : Source HiveServer2 URI
   * targetHiveServer2Uri : Target HiveServer2 URI
   * sourceDataset : Hive Database as source dataset
   * retryAttempts : Retry count (optional)
   * retryDelay : Retry delay  (optional)
   * maxEvents : Number of events to process (optional)

This document describes REST APIs to manage the clusters and policies for the Beacon replication engine.
Supported functionalities include:

*Cluster*

. link:#\_post_api_beacon_cluster_submit_cluster_name[Submit cluster]
. link:#\_get_api_beacon_cluster_list[List clusters]
. link:#\_get_api_beacon_cluster_status_cluster_name[Get cluster status]
. link:#\_get_api_beacon_cluster_getentity_cluster_name[Get cluster]
. link:#\_delete_api_beacon_cluster_delete_cluster_name[Delete cluster]

*Policy:*

On the source cluster only read operations on policy entity is allowed.
Read or write Instance related operations are not allowed on source for Policy.
It is recommended to perform any kind of operation on target cluster to get uptodate information instead of stale information.

If the destination of a FS replication policy is HCFS only then write operations are allowed on source cluster.
User will get This operation is not allowed on source cluster: <sourceClusterName>. Try it on target cluster <targetClusterName> error.

. link:#\_post_api_beacon_policy_submit_policy_name[Submit replication policy]
. link:#\_post_api_beacon_policy_schedule_policy_name[Schedule an replication policy]
. link:#\_post_api_beacon_policy_submitandschedule_policy_name[Submit and schedule an replication policy]
. link:#\_get_api_beacon_policy_list[List replication policies]
. link:#\_get_api_beacon_policy_status_policy_name[Get Replication policy status]
. link:#\_get_api_beacon_policy_getentity_policy_name[Get Replication policy definition]
. link:#\_post_api_beacon_policy_suspend_policy_name[Suspend Replication policy]
. link:#\_post_api_beacon_policy_resume_policy_name[Resume Replication policy]
. link:#\_delete_api_beacon_policy_delete_policy_name[Delete Replication policy]


*Pairing & Unpairing:*

. link:#\_post_api_beacon_cluster_pair[Pair cluster with remote cluster to initiate replication]
. link:#\_post_api_beacon_cluster_unpair[Unpair cluster with remote cluster to initiate replication]

*Events:*

Supported Beacon events with severity are :

    * started - INFO
    * stopped - INFO
    * submitted - INFO
    * deleted - WARN
    * paired - INFO
    * synced - INFO
    * scheduled - INFO
    * succeeded - INFO
    * failed - ERROR
    * ignored - INFO
    * killed - ERROR


List of Event Entity types :

    * system
    * cluster
    * policy
    * policyinstance

Events Rest API

. link:#\_get_api_beacon_events_policy_policy_name[Get Events using Policy Name]
. link:#\_get_api_beacon_events_event_name[Get Events using Event Name and Type]
. link:#\_get_api_beacon_events_entity_entity_type[Get events using entity type]
. link:#\_get_api_beacon_events_all[Get all generated events]
. link:#\_get_api_beacon_events_instance[Get particular instance event]

*Logs:*

. link:#\_get_api_beacon_logs[Get beacon logs]

POST api/beacon/cluster/submit/:cluster-name
--------------------------------------------

*Description:* Submit a cluster.

*Parameters:* _:cluster-name_ Name of the cluster.

*Note:* *cluster-name* can contain the data center value. In that case, dataCenter and clusterName are separated by single '$'
 character.

*REST Call:* POST http://localhost:25968/api/beacon/cluster/submit/primaryCluster

[source, properties]
fsEndpoint=hdfs://localhost:8020
beaconEndpoint=http://localhost:25968
hsEndpoint=http://localhost:10000
description=primary cluster
local=true
user=ambari-qa
tags=consumer=consumer@xyz.com,owner=producer@xyz.com
dfs.namenode.kerberos.principal=hdfs/_HOST@YOUR-REALM.COM

*Response:*

[source, json]
{
   "requestId":"e5cc8230-f356-4566-9b65-536abdff8aa3",
   "message":"Submit successful (CLUSTER) primaryCluster",
   "status":"SUCCEEDED"
}

*Note:* dfs.namenode.kerberos.principal is custom property

Example of a cluster submission with data center in the cluster name.

*REST Call:* POST http://localhost:25968/api/beacon/cluster/submit/dataCenter$source

[source, properties]
fsEndpoint=hdfs://localhost:8020
beaconEndpoint=http://localhost:25968
hsEndpoint=http://localhost:10000
description=source cluster
local=false
user=ambari-qa
tags=consumer=consumer@xyz.com,owner=producer@xyz.com
dfs.namenode.kerberos.principal=hdfs/_HOST@YOUR-REALM.COM

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "Submit successful (CLUSTER) dataCenter$source",
  "requestId": "310412574@qtp-1676010932-0"
}

GET api/beacon/cluster/list
---------------------------

*Description:* List cluster entities

*Parameters:*

* *_fields_* <optional> Entity output fields separated by commas. Valid options are peers and tags.
* *_orderBy_* <optional> Column by which results should be ordered. Sorted by descending order. Valid options are nominalTime (default) and status.
* *_sortOrder_* <optional> Valid options are _asc_ and _desc_
* *_offset_* <optional> Show results from the offset. Used for pagination. Negative offset are reset to 0. Default is 0.
* *_numResults_* <optional> Number of instances per entity to show. Default value is 10.

*REST Call:* GET http://localhost:25968/api/beacon/cluster/list?fields=peers,tags

*Response:*
[source, json]
{
	"totalResults": 2,
	"results": 2,
	"cluster": [{
			"name": "backupCluster",
			"peers": ["primaryCluster"],
			"tags": ["consumer=consumer@xyz.com", "owner=producer@xyz.com"]
		},
		{
			"name": "primaryCluster",
			"peers": ["backupCluster"],
			"tags": ["consumer=consumer@xyz.com", "owner=producer@xyz.com"]
		}
	]
}

GET api/beacon/cluster/status/:cluster-name
-------------------------------------------

*Description:* Get status of the cluster

*Parameters:* _:cluster-name_ Name of the cluster

*REST Call:* GET http://localhost:25968/api/beacon/cluster/status/:cluster-name

*Response:*

* If request is successful:
[source, json]
{
  "name": "target",
  "status": "SUBMITTED"
}

* If request fails:
[source, json]
{
  "status": "FAILED",
  "message": "wrongCluster (CLUSTER) not found",
  "requestId": "876823802@qtp-1500379239-0"
}

GET api/beacon/cluster/getEntity/:cluster-name
----------------------------------------------

*Description:* Get cluster definition

*Parameters:* _:cluster-name_ Name of the cluster

*REST Call:* GET http://localhost:25968/api/beacon/cluster/getEntity/primaryCluster

*Response:*

[source, json]
{
   "name":"primaryCluster",
   "description":"primary",
   "fsEndpoint":"hdfs://localhost:8020",
   "hsEndpoint":"http://localhost:10000",
   "local": false,
   "tags":"consumer=consumer@xyz.com,owner=producer@xyz.com",
   "peers":"c1, c2",
   "customProperties":{
      "dfs.namenode.kerberos.principal":"hdfs/_HOST@YOUR-REALM.COM"
   },
   "user":"ambari-qa",
   "entityType":"CLUSTER"
}

*Note:* peers:"c1, c2" is the list of remote clusters with which this cluster has been paired for replication purposes.

DELETE api/beacon/cluster/delete/:cluster-name
----------------------------------------------

*Description:* Delete cluster

*Parameters:* _:cluster-name_ Name of the cluster

*REST Call:* DELETE http://localhost:25968/api/beacon/cluster/delete/primaryCluster[__http://localhost:25968/api/beacon/cluster/delete/primaryCluster__]

*Response:*

[source, json]
{
"requestId": "qtp2026718042-1933333",
"message": "primaryCluster(CLUSTER) removed successfully",
"status": "SUCCEEDED"
}

POST api/beacon/policy/submit/:policy-name
------------------------------------------

*Description:* Submit an replication policy.

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25968/api/beacon/policy/submit/hdfsPolicy

[source, properties]
name=hdfsPolicy
description=hdfs daily policy
type=FS
sourceDataset=/user/ambari-qa/data
targetDataset=/user/ambari-qa/data
sourceCluster=primaryCluster
targetCluster=backupCluster
frequencyInSec=3600
distcpMaxMaps=5
distcpMapBandwidth=10
tdeEncryptionEnabled=true
userName=ambari-qa
queueName=default


*Response:*

[source, json]
 {
     "status": "SUCCEEDED",
     "message": "Submit successful (REPLICATIONPOLICY) hdfsPolicy",
     "requestId": "181326224@qtp-1407167674-0"
 }

*Note:* queueName is custom properties, if not specified "default" queue will be used.

POST http://localhost:25968/api/beacon/policy/submit/hivePolicy

[source, properties]
name=hivePolicy
description=hive daily policy
type=HIVE
dataset=sales <Database to replicate>
sourceCluster=primaryCluster
targetCluster=backupCluster
frequencyInSec=3600
tags=owner=producer@xyz.com,component=sales
user=ambari-qa
retryAttempts=3
maxEvents=-1

*Response:*

[source, json]
{
   "requestId":"qtp2026718042-19",
   "message":"Submit successful (REPLICATIONPOLICY) hivePolicy",
   "status":"SUCCEEDED"
}

*Note:* maxEvents is custom properties

POST api/beacon/policy/schedule/:policy-name
--------------------------------------------

*Description:* Schedule submitted policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25968/api/beacon/policy/schedule/hivePolicy

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "hdfspolicy(REPLICATIONPOLICY) scheduled successfully",
  "requestId": "1223050066@qtp-1933129092-0"
}

POST api/beacon/policy/submitAndSchedule/:policy-name
-----------------------------------------------------

*Description:* Submit and schedule an replication policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25968/api/beacon/policy/submit/hivePolicy[__http://localhost:25968/api/beacon/policy/submitAndSchedule/hivePolicy__]

[source, properties]
name=hivePolicy
description=hive daily policy
type=HIVE
dataset=sales <Database to replicate>
sourceCluster=primaryCluster
targetCluster=backupCluster
frequencyInSec=3600
tags=owner=producer@xyz.com,component=sales
user=ambari-qa
retryAttempts=3
maxEvents=-1

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "Policy [hdfspolicy] submitAndSchedule successful",
  "requestId": "1917442783@qtp-1933129092-1"
}

*Note:* maxEvents is custom properties

GET api/beacon/policy/list
--------------------------

*Description:* List replication policies.

*Parameters:* All the parameters are optional.

* *_fields:_* Entity output fields separated by commas. Valid options are status, tags, clusters, datasets, instances, frequency, starttime and endtime.
* *_orderBy:_* Column by which results should be ordered. Valid options are name, status, type, sourcecluster, targetcluster, starttime, endtime and frequency.
* *_sortOrder:_* Valid options are 'asc' and 'desc'. Default is 'asc'.
* *_offset:_* Show results from the offset. Used for pagination. Negative offset are reset to 0. Default is 0.
* *_numResults:_* Number of instances per entity to show. Default value is 10.
* *_filterBy:_* Filter results by list of *field:value* pairs. Supported filter fields are name, status, type, sourcecluster and targetcluster.
* *_instanceCount:_* Number of recent instances for the policy. The recent instances are based on their startTime in DESC order.

*Example:* filterBy=sourcecluster:primaryCluster,targetcluster:backupCluster|thirdCluster

Query will do an *AND* among _filterBy_ fields. | within same filter field does an *OR*.

The 'instances' will be an JSON array of policy instance information same as provided into instance list API.
Instances execute on the target cluster and instance data will be available only on the target beacon server.


*REST Call:* GET http://localhost:25968/api/beacon/policy/list?fields=status,tags,clusters,frequency,endtime,datasets

*Response:*

[source, json]
{
  "totalResults": 1,
  "results": 1,
  "policy": [
    {
      "policyId": "/source/source/hdfspolicy/0/1496123912666/000000002",
      "type": "FS",
      "name": "hdfspolicy",
      "description": "daily data policy",
      "status": "SUBMITTED",
      "endTime": "9999-12-31T00:00:00",
      "sourceCluster": "source",
      "targetCluster": "target",
      "sourceDataset": "/tmp/test",
      "targetDataset": "/tmp/test",
      "frequencyInSec": 60,
      "tags": []
    }
  ]
}

GET api/beacon/policy/status/:policy-name
-----------------------------------------

*Description:* Get status of the policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* GET http://localhost:25968/api/beacon/policy/status/hivePolicy

*Response:*

* If request is successful:
[source, json]
{
  "name": "hivePolicy",
  "status": "RUNNING"
}

*Note:* Different status values for a policy: _SUBMITTED_, _RUNNING_, _SUSPENDED_.

* If request fails:
[source, json]
{
  "status": "FAILED",
  "message": "Policy does not exists name: hivePolicy",
  "requestId": "1223050066@qtp-1933129092-0"
}


GET api/beacon/policy/getEntity/:policy-name
--------------------------------------------

*Description:* Get policy definition

*Parameters:*

* *_policy-name:_* Name of the replication policy.
* *_archived:_* default: false, Allow to retrieve the deleted policies.


*REST Call:* GET http://localhost:25968/api/beacon/policy/getEntity/hdfspolicy

*Response:*

[source, json]
{
  "totalResults": 1,
  "results": 1,
  "policy": [
    {
      "policyId": "/source/source/hdfspolicy/0/1496123912666/000000002",
      "type": "FS",
      "name": "hdfspolicy",
      "description": "daily data policy",
      "status": "SUBMITTED",
      "executionType": "FS",
      "sourceDataset": "/tmp/test",
      "targetDataset": "/tmp/test",
      "sourceCluster": "source",
      "targetCluster": "target",
      "endTime": "9999-12-31T00:00:00",
      "frequencyInSec": 60,
      "customProperties": {
        "distcpMapBandwidth": "10",
        "targetSnapshotRetentionAgeLimit": "10",
        "sourceSnapshotRetentionNumber": "1",
        "distcpMaxMaps": "1",
        "preserveAcl": "false",
        "queueName": "default",
        "tdeEncryptionEnabled": "false",
        "preservePermission": "true",
        "targetSnapshotRetentionNumber": "1",
        "sourceSnapshotRetentionAgeLimit": "10"
      },
      "user": "ambari-qa",
      "retryAttempts": 3,
      "retryDelay": 1800
    }
  ]
}

POST api/beacon/policy/suspend/:policy-name
-------------------------------------------

*Description:* Suspend a policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25968/api/beacon/policy/suspend/hdfspolicy

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "hdfspolicy(FS) suspended successfully",
  "requestId": "1223050066@qtp-1933129092-0"
}

POST api/beacon/policy/resume/:policy-name
------------------------------------------

*Description:* Resume a policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25968/api/beacon/policy/resume/hdfspolicy

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "hdfspolicy(FS) resumed successfully",
  "requestId": "1223050066@qtp-1933129092-0"
}

DELETE api/beacon/policy/delete/:policy-name
--------------------------------------------

*Description:* Delete policy

*Parameters:* _:policy-name_ Name of the policy

*REST Call:* DELETE http://localhost:25968/api/beacon/policy/delete/hdfsPolicy

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "hdfspolicy(FS) removed successfully.",
  "requestId": "1223050066@qtp-1933129092-0"
}

POST api/beacon/cluster/pair
----------------------------

*Description:* Pair the clusters

*Parameters:* _Remote cluster name_ +

*REST Call:* POST _http://localhost:25968/api/beacon/pair[http://localhost:25968/api/beacon/cluster/pair]?remoteClusterName=backupCluster_ +

*Response:*

[source, json]
{
"requestId": "qtp2026718042-1933333",
"message": "Clusters successfully paired",
"status": "SUCCEEDED"
}

POST api/beacon/cluster/unpair
------------------------------

*Description:* Unpair the clusters

*Parameters:* _Remote cluster name_

*REST Call:* POST _http://localhost:25968/api/beacon/pair[http://localhost:25968/api/beacon/cluster/unpair]?remoteClusterName=backupCluster_ +

*Response:*

[source, json]
{
"requestId": "qtp2026718042-1933333",
"message": "Clusters successfully unpaired",
"status": "SUCCEEDED"
}

GET api/beacon/policy/info/:policy-name
---------------------------------------

*Description:* Get type of the submitted replication policy

*Parameters:* :policy-name Name of the replication policy

*REST Call:* GET http://localhost:25968/api/beacon/policy/type/hdfsdr[http://localhost:25968/api/beacon/policy/info/hdfsdr]

*Response:*

[source, json]
{
"requestId": "1549725679@qtp-1818544933-0",
"type": "FS"
}

GET /api/beacon/policy/instance/list/:policy-name
-------------------------------------------------

*Description:* Get the list of policy instance. This does not allow listing the policy instance on source cluster.

*Parameters:* All the parameters are optional.

* *_filterBy:_* Each filter needs to be provided into a *key:value* pair format and different pairs will be separated by comma (,). The logical *AND* operation is used between all the provided filters.
* *_orderBy:_* default: startTime
* *_sortOrder:_* default: ASC
* *_offset:_* Show results from the offset. Used for pagination. Negative offset are reset to 0. Default is 0.
* *_numResults:_* default: 10 and max: 1000
* *_archived:_* default: false, Allow to retrieve the instances of deleted policies.

Supported *_filterBy_* fields are: *status*, *type*, *startTime*, *endTime*.

Date should be in the Beacon supported format i.e. : *yyyy-MM-dd'T'HH:mm:ss*.

Policy instance statuses are: *SUCCESS*, *FAILED*, *KILLED*.

_message_ is optional (as it is populated upon instance completion) and contains detailed information about the instance. In case of failure, it will have the failure reason information.

*REST Call:* http://localhost:25968/api/beacon/policy/instance/list?filterBy=type:fs&numResults=1&sortOrder=DESC

*Response:*

[source, json]
{
  "totalResults": 1,
  "results": 1,
  "instance": [
    {
        "id": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1496130472216/000000001@1",
        "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1496130472216/000000001",
        "name": "hdfsdr",
        "type": "FS",
        "executionType": "FS",
        "user": "pbishnoi",
        "status": "SUCCESS",
        "trackingInfo": "{\"jobId\":\"job_1498545389800_0074\",\"jobType\":\"MAIN\",\"totalMapTasks\":6,\"completedMapTasks\":6,\"bytesCopied\":642311417,\"filesCopied\":549,\"timeTaken\":66591}",
        "startTime": "2017-05-30T07:47:58",
        "endTime": "2017-05-30T07:49:36",
        "retryAttempted": "0",
        "message": "SUCCESS"
    }
  ]
}

*NOTE:* trackingInfo field is optional, for failed job it might not be available.

GET /api/beacon/instance/list
-----------------------------

*Description:* Get the list of policy instance. When queried on a source cluster it will return empty list.

*Parameters:*

* *_filterBy:_* Each filter needs to be provided into a *key:value* pair format and different pairs need be separated by comma (,). The logical *AND* operation is used between all the provided filters.
* *_orderBy:_* default: startTime
* *_sortOrder:_* default: ASC
* *_offset:_* Show results from the offset. Used for pagination. Negative offset are reset to 0. Default is 0.
* *_numResults:_* default: 10 and max: 1000
* *_archived:_* default: false, Allow to retrieve the instances of deleted policies.

Supported *_filterBy_* fields are: *name*, *status*, *type*, *startTime*, *endTime*.

Date should be in the Beacon supported format i.e. : *yyyy-MM-dd'T'HH:mm:ss*.

Policy instance statuses are: *SUCCESS*, *FAILED*, *KILLED*.

_message_ is optional (as it is populated upon instance completion) and contains detailed information about the instance. In case of failure, it will have the failure reason information.

*REST Call:* http://localhost:25968/api/beacon/instance/list?filterBy=type:fs&numResults=1&sortOrder=DESC

*Response:*

[source, json]
{
  "totalResults": 1,
  "results" : 1,
  "instance": [
    {
        "id": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1496130472216/000000001@1",
        "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1496130472216/000000001",
        "name": "hdfsdr",
        "type": "FS",
        "executionType": "FS",
        "user": "pbishnoi",
        "status": "SUCCESS",
        "trackingInfo": "{\"jobId\":\"job_1498545389800_0074\",\"jobType\":\"MAIN\",\"totalMapTasks\":6,\"completedMapTasks\":6,\"bytesCopied\":642311417,\"filesCopied\":549,\"timeTaken\":66591}",
        "startTime": "2017-05-30T07:47:58",
        "endTime": "2017-05-30T07:49:36",
        "retryAttempted": "0",
        "message": "SUCCESS"
    }
  ]
}

*NOTE:* trackingInfo field is optional, for failed job it might not be available.

POST /api/beacon/policy/instance/abort/:policy-name
---------------------------------------------------

*Description:* Abort a policy instance currently executing.

*Parameters:* :policy-name name of the policy whose running instance needs to be aborted.

*REST Call:* http://localhost:25968/api/beacon/policy/instance/abort/daily-user-policy

*Response:*

* When an instance of the policy is in execution.
[source, json]
{
  "status": "SUCCEEDED",
  "message": "policy instance abort status [true]",
  "requestId": "1223050066@qtp-1933129092-0"
}

* When no instance is in execution.
[source, json]
{
  "status": "SUCCEEDED",
  "message": "policy instance abort status [false]",
  "requestId": "1223050066@qtp-1933129092-0"
}

* When Policy is not in _RUNNING_ state. (_SUBMITTED_ or _SUSPENDED_ state)
[source, json]
{
  "status": "FAILED",
  "message": "Policy [daily-user-policy] is not in [RUNNING] state. Current status [SUBMITTED]",
  "requestId": "1223050066@qtp-1933129092-0"
}

POST /api/beacon/policy/instance/rerun/:policy-name
---------------------------------------------------

*Description:* Rerun last FAILED/KILLED policy instance.

* Policy should be into the RUNNING state.
* Allows rerunning only the latest instance of the policy. The latest instance of policy should be into FAILED/KILLED state.
* The rerun starts from the last failed job in the instance.

*Parameters:* :policy-name name of the policy whose latest instance to be rerun.

*REST Call:* http://localhost:25968/api/beacon/policy/instance/rerun/daily-user-policy

*Response:*

* Successful rerun of the policy instance:
[source, json]
{
    "status": "SUCCEEDED",
    "message": "Policy instance /source/source/target/target/policy-1/0/1501762737151/000000001@1 is scheduled for immediate rerun successfully.",
    "requestId": "369351727@qtp-2029709919-0"
}

* Policy is not in the RUNNING state:
[source, json]
{
    "status": "FAILED",
    "message": "Policy [policy-1] is not in [RUNNING] state. Current status [SUSPENDED]",
    "requestId": "369351727@qtp-2029709919-0"
}

* Latest policy instance is not in FAILED/KILLED state.
[source, json]
{
    "status": "FAILED",
    "message": "Policy instance is not in FAILED/KILLED state. Last instance: /source/source/target/target/policy-1/0/1501762737151/000000001@15 status: RUNNING.",
    "requestId": "369351727@qtp-2029709919-0"
}

GET api/beacon/events/policy/:policy_name
-----------------------------------------
*Description:* Get events based on policy name

*Parameters:*

* *_policy_name_*    :     Name of the policy
* *_start_*          :     start date from which events is to get (optional)
* *_end_*            :     end date upto which events is to get (optional)
* *_orderBy_*        :     Event field on which results is to sort (optional). Default : eventTimeStamp
* *_sortOrder_*      :     ASC|DESC (optional). Default : DESC.
* *_offset_*         :     Show results from offset. Used for pagination. Negative offset are reset to 0. Default is 0.
* *_numResults_*     :     Number of events to show. Default value is 10

*REST call:* GET http://localhost:25968/api/beacon/events/policy/:policy_name

*Example:* http://locahost:25968/api/beacon/events/policy/hdfsdr

*Response:*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalResults": 3,
  "results": 3,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002@1",
      "event": "succeeded",
      "eventType": "policyinstance",
      "severity": "info",
      "timestamp": "2017-05-16 08:59:00.491",
      "message": "policy instance succeeded"
    },
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
      "event": "scheduled",
      "eventType": "policy",
      "severity": "info",
      "timestamp": "2017-05-16 08:58:16.279",
      "message": "replication policy scheduled"
    },
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
      "event": "submitted",
      "eventType": "policy",
      "severity": "info",
      "timestamp": "2017-05-16 08:58:12.809",
      "message": "replication policy submitted"
    }
  ]
}

*Example:* http://sourcecluster:25968/api/beacon/events/policy/hdfsdr

Above rest call will return policy details from source cluster with flag

syncEvent=true, which signify that policy synced successfully on source cluster

after submission on target cluster.

[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "664969353@qtp-81722690-0",
  "totalResults": 1,
  "results": 1,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1495850268439/000000001",
      "event": "submitted",
      "eventType": "policy",
      "severity": "info",
      "syncEvent": true,
      "timestamp": "2017-05-27 01:57:49.838",
      "message": "replication policy submitted"
    }
  ]
}

*Note:* By default API results will be sorted by timestamp in descending order.

Supported event fields for ordering are policyId, instanceId, eventId, eventEntityType, eventSeverity, eventTimeStamp.

GET api/beacon/events/:event_name
----------------------------------
*Description:* Get particular events on base of event_name

*Parameters:*

* *_event_name_*     :     Name of event
* *_start_*          :     start date from which events is to get (optional)
* *_end_*            :     end date upto which events is to get (optional)
* *_orderBy_*        :     Event field on which results is to sort (optional). Default : eventTimeStamp
* *_sortOrder_*      :     ASC|DESC (optional). Default : DESC.
* *_offset_*         :     Show results from offset. Used for pagination. Negative offset are reset to 0. Default is 0.
* *_numResults_*     :     Number of events to show. Default value is 10

*REST call:* GET http://localhost:25968/api/beacon/events/:event_name

*Example:* http://localhost:25968/api/beacon/events/submitted

*Response:*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalResults": 4,
  "results": 4,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
      "event": "submitted",
      "eventType": "policy",
      "severity": "info",
      "timestamp": "2017-05-16 08:58:12.809",
      "message": "replication policy submitted"
    },
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000001",
      "event": "submitted",
      "eventType": "policy",
      "severity": "info",
      "timestamp": "2017-05-16 08:43:48.917",
      "message": "replication policy submitted"
    },
    {
      "event": "submitted",
      "eventType": "cluster",
      "severity": "info",
      "timestamp": "2017-05-16 08:34:49.225",
      "message": "cluster entity submitted"
    },
    {
      "event": "submitted",
      "eventType": "cluster",
      "severity": "info",
      "timestamp": "2017-05-16 08:34:46.068",
      "message": "cluster entity submitted"
    }
  ]
}

GET http://localhost:25968/api/beacon/events/succeeded
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalResults": 2,
  "results": 2,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002@84",
      "event": "succeeded",
      "eventType": "policyinstance",
      "severity": "info",
      "timestamp": "2017-05-16 12:26:11.218",
      "message": "policy instance succeeded"
    },
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002@83",
      "event": "succeeded",
      "eventType": "policyinstance",
      "severity": "info",
      "timestamp": "2017-05-16 12:23:41.438",
      "message": "policy instance succeeded"
    }
  ]
}

GET http://localhost:25968/api/beacon/events/succeeded?numResults=15&orderBy=eventEntityType&sortOrder=desc

*Note:* By default API results will be sorted by timestamp in descending order.

Supported event fields for ordering are policyId, instanceId, eventId, eventEntityType, eventSeverity, eventTimeStamp.

GET api/beacon/events/entity/:entity_type
-----------------------------------------

*Description:* Get events for entity type i.e system, cluster and policy

*Parameters:*

* *_entity_type_*    :     entity type can be system, cluster or policy
* *_start_*          :     start date from which events is to get (optional)
* *_end_*            :     end date upto which events is to get (optional)
* *_orderBy_*        :     Event field on which results is to sort (optional). Default : eventTimeStamp
* *_sortOrder_*      :     ASC|DESC (optional). Default : DESC.
* *_offset_*         :     Show results from offset. Used for pagination. Negative offset are reset to 0. Default is 0.
* *_numResults_*     :     Number of events to show. Default value is 10


*REST call:* GET  http://localhost:25968/api/beacon/events/entity/system

*Response*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalResults": 2,
  "results": 2,
  "events": [
    {
      "policyId": "0.0.0.0",
      "event": "started",
      "eventType": "system",
      "severity": "info",
      "timestamp": "2017-05-16 14:10:54.369",
      "message": "beacon started successfully"
    },
    {
      "policyId": "0.0.0.0",
      "event": "stopped",
      "eventType": "system",
      "severity": "info",
      "timestamp": "2017-05-16 14:10:16.921",
      "message": "beacon stopped successfully"
    }
  ]
}

GET  http://localhost:25968/api/beacon/events/entity/cluster

GET http://localhost25968/api/beacon/events/entity/cluster?start=2017-03-16T00:00:00&end=2017-03-23T00:00:00&numResults=1&offset=1

GET http://localhost:25968/api/beacon/events/entity/policy?start=2017-05-16T00:00:00&end=2017-05-20T00:00:00&numResults=5&offset=1

GET http://localhost:25968/api/beacon/events/entity/policyinstance?start=2017-05-16T00:00:00&end=2017-05-20T00:00:00&numResults=15&offset=1

*Note:* By default API results will be sorted by timestamp in descending order.

Supported event fields for ordering are policyId, instanceId, eventId, eventEntityType, eventSeverity, eventTimeStamp.


GET api/beacon/events/all
-------------------------
*Description:* Get all events in Beacon

*Parameters:*

* *_start_*          :     start date from which events is to get (optional)
* *_end_*            :     end date upto which events is to get (optional)
* *_orderBy_*        :     Event field on which results is to sort (optional). Default : eventTimeStamp
* *_sortOrder_*      :     ASC|DESC (optional). Default : DESC.
* *_offset_*         :     Show results from offset. Used for pagination. Negative offset are reset to 0. Default is 0.
* *_numResults_*     :     Number of events to show. Default value is 10

*REST call:* GET http://localhost:25968/api/beacon/events/all

*Response:*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalResults": 2,
  "results": 2,
  "events": [
    {
        "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
        "instanceId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002@101",
        "event": "succeeded",
        "eventType": "policyinstance",
        "severity": "info",
        "timestamp": "2017-05-16 13:08:44.713",
        "message": "policy instance succeeded"
    },
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002@100",
      "event": "succeeded",
      "eventType": "policyinstance",
      "severity": "info",
      "timestamp": "2017-05-16 13:06:06.011",
      "message": "policy instance succeeded"
    }
  ]
}

GET http://localhost:25968/api/beacon/events/all?numResults=15&orderBy=eventEntityType&sortOrder=desc

*Note:* By default API results will be sorted by timestamp in descending order.

Supported event fields for ordering are policyId, instanceId, eventId, eventEntityType, eventSeverity, eventTimeStamp.


GET api/beacon/events/instance
------------------------------

*Description:* Get particular policy instance id events

*Parameters:*

* *_instanceId_*     :     Instance Id for which events are required

*REST call:* GET http://localhost:25968/api/beacon/events/instance?instanceId=/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002@104

*Response:*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalResults": 1,
  "results": 1,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1494924228843/000000002@104",
      "event": "succeeded",
      "eventType": "policyinstance",
      "severity": "info",
      "timestamp": "2017-05-16 13:16:06.614",
      "message": "policy instance succeeded"
    }
  ]
}

GET api/beacon/logs
-------------------
 *Description:* Get Beacon logs using filter field.

 *Parameters:*

 * *_filterBy:_* Filter needs to be provided into a *key:value* pair format.
 * *_start:_*  start date time from which logs need to obtain. (optional)
 * *_end:_*  end date time upto which logs need to obtain. (optional)
 * *_frequency:_* time period for which last hourly logs need to be looked for specified filter field, if start time is null. (default 12 hours)
 * *_numResults:_* number of logs messages required to be fetched. (default 100)

 Supported *_filterBy_* fields are: *user*, *cluster*, *policyname*, *policyid*, *instanceid*.

 DateTime should be in the Beacon supported format i.e. : *yyyy-MM-dd'T'HH:mm:ss*.

 *REST Call:* GET http://localhost:25968/api/beacon/logs?filterBy=user:ambari-qa

 *Response:*
 [source, json]
 {
   "status": "SUCCEEDED",
   "message": "2017-05-17 08:30:58,549 INFO  - [main:] ~ main-1 USER[ambari-qa] CLUSTER[beacontarget] App path: /home/ambari-qa/beacon-1.0.0.2.6.0.1-SNAPSHOT/server/webapp/beacon (Main:182)\n2017-05-17 08:30:58,551 INFO  - [main:] ~ main-1 USER[ambari-qa] CLUSTER[beacontarget] Beacon cluster: beacontarget (Main:182)\n",
   "requestId": "1844638642@qtp-948395645-2"
 }


 *REST Call:* http://localhost:25968/api/beacon/logs?filterBy=policyid:/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1495009895429/000000001&start=2017-05-15T00:00:00&end=2017-05-18T20:00:00&numResults=5

 *Response:*
 [source, json]
 {
   "status": "SUCCEEDED",
   "message": "2017-05-17 08:31:42,420 INFO  - [QuartzScheduler_Worker-1:] ~ QuartzScheduler_Worker-1-19 POLICYID[/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1495009895429/000000001] INSTANCEID[/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1495009895429/000000001@1] policy instance [/beaconsource/beaconsource/beacontarget/beacontarget/hdfsdr/0/1495009895429/000000001@1] to be executed. (QuartzJobListener:182)\n",
   "requestId": "1844638642@qtp-948395645-2"
 }


GET api/beacon/admin/version
----------------------------

*Description:* Get Beacon server version information.

*REST Call:* GET http://localhost:25968/api/beacon/admin/version

*Response:*
[source, json]
{
    "status": "RUNNING",
    "version": "1.0.0.2.6.0.0-SNAPSHOT"
}

GET api/beacon/admin/status
----------------------------

*Description:* Get Beacon server status information.

*plugins:* List of comma (,) separated plugins configured in the Beacon.

*REST Call:* GET http://localhost:25968/api/beacon/admin/status

*Response:*
[source, json]
{
    "status": "RUNNING",
    "version": "1.0.0.2.6.0.0-SNAPSHOT",
    "plugins": "None",
    "security": "None",
    "wireEncryption": false
}

Response with plugins enabled.

*Response:*
[source, json]
{
    "status": "RUNNING",
    "version": "1.0.0.2.6.0.0-SNAPSHOT",
    "plugins": "RANGER,ATLAS",
    "security": "None",
    "wireEncryption": false
}