//<!--
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License. See accompanying LICENSE file.
//-->

= Beacon REST API


Beacon replication engine defines cluster and replication policy entities to maintain information about clusters and policies involved in replication.
The cluster entities are persisted on File system as yml files and Policy entities are persisted into configured database.
It also has in-memory lookup of cluster entities for faster access.

*Cluster definition:*

* *name:* Name of the cluster <mandatory>
* *description:* Description of the cluster <mandatory>
* *fsEndpoint:* HDFS end point <mandatory>
* *beaconEndpoint:* Beacon service endpoint <mandatory>
* *hsEndpoint:* Hive server2 end point <mandatory for Hive replication>
* *tags:* Cluster tags <Optional. <key, value> pairs>

*Note:* Custom properties can be passed as <key, value> pairs. E.g. dfs.namenode.kerberos.principal=hdfs/_HOST@YOUR-REALM.COM

*Replication policy definition:*

* *name:* Name of the policy <mandatory>
* *type:* {FS|HIVE|HBASE} <mandatory>
* *sourceDataset:* {FS path | Hive DB } <mandatory>
* *sourceCluster:* Replication source cluster name <mandatory>
* *targetCluster:* Replication target cluster name <mandatory>
* *startTime:* Replication job start time. Date passed should be in the format "yyyy-MM-dd'T'HH:mm:ss" and UTC timezone <Optional>
* *endTime:* Replication job end time. Date passed should be in the format "yyyy-MM-dd'T'HH:mm:ss" and UTC timezone <Optional>
* *frequencyInSec:* Frequency of replication job in seconds <mandatory>
* *tags:* Tags of replication job <Optional. <key, value> pairs>
* *retryDelayInSec:* Delay after which job should be retries in case of failure in seconds <Optional>. Default value is 1800s.
* *retryAttempts:* Number of retry attempts <Optional>. Default value is 3.

For FS replication type where it is HDFS <-> HDFS replication, Beacon supports following DistCP options which are optional and can be passed in the custom properties.
Allowed values for these are true or false.

* overwrite [Can take values true or false]

* ignoreErrors

* skipChecksum
* removeDeletedFiles
* preserveBlockSize
* preserveReplicationNumber
* preservePermission
* preserveUser
* preserveGroup
* preserveChecksumType
* preserveAcl
* preserveXattr
* preserveTimes

For more details about DistCP options refer https://hadoop.apache.org/docs/r1.2.1/distcp2.html[_DistCP V2 guide_]. E.g:

removeDeletedFiles=true +
preserveUser=true +
preserveGroup=true +

For HDFS <-> HCFS refer https://docs.google.com/document/d/1PoXt2yOiZXP6IK8FNdX9eEdfZznHxfY01ebGnIYw_ro/edit#[_Beacon HCFS behavior_] document.

This document describes REST APIs to manage the clusters and policies for the Beacon replication engine.
Supported functionalities include:

*Cluster*

. link:#\_post_api_beacon_cluster_submit_cluster_name[Submit cluster]
. link:#\_get_api_beacon_cluster_list[List clusters]
. link:#\_get_api_beacon_cluster_status_cluster_name[Get cluster status]
. link:#\_get_api_beacon_cluster_getentity_cluster_name[Get cluster]
. link:#\_delete_api_beacon_cluster_delete_cluster_name[Delete cluster]

*Policy:*

On the source cluster only read operations on policy entity is allowed.
Read or write Instance related operations are not allowed on source for Policy.
It is recommended to perform any kind of operation on target cluster to get uptodate information instead of stale information.

If the destination of a FS replication policy is HCFS only then write operations are allowed on source cluster.
User will get This operation is not allowed on source cluster: <sourceClusterName>. Try it on target cluster <targetClusterName> error.

. link:#\_post_api_beacon_policy_submit_policy_name[Submit replication policy]
. link:#\_post_api_beacon_policy_schedule_policy_name[Schedule an replication policy]
. link:#\_post_api_beacon_policy_submitandschedule_policy_name[Submit and schedule an replication policy]
. link:#\_get_api_beacon_policy_list[List replication policies]
. link:#\_get_api_beacon_policy_status_policy_name[Get Replication policy status]
. link:#\_get_api_beacon_policy_getentity_policy_name[Get Replication policy definition]
. link:#\_post_api_beacon_policy_suspend_policy_name[Suspend Replication policy]
. link:#\_post_api_beacon_policy_resume_policy_name[Resume Replication policy]
. link:#\_delete_api_beacon_policy_delete_policy_name[Delete Replication policy]


*Pairing & Unpairing:*

. link:#\_post_api_beacon_cluster_pair[Pair cluster with remote cluster to initiate replication]
. link:#\_post_api_beacon_cluster_unpair[Unpair cluster with remote cluster to initiate replication]

*Events:*

. link:#\_get_api_beacon_events_policy_policy_name[Get Events using Policy Name]
. link:#\_get_api_beacon_events_event_name[Get Events using Event Name and Type]
. link:#\_get_api_beacon_events_entity_entity_type[Get events using entity type]
. link:#\_get_api_beacon_events_all[Get all generated events]
. link:#\_get_api_beacon_events_instance[Get particular instance event]

*Logs:*

. link:#\_get_api_beacon_logs[Get beacon logs]

POST api/beacon/cluster/submit/:cluster-name
--------------------------------------------

*Description:* Submit a cluster.

*Parameters:* _:cluster-name_ Name of the cluster

*Note:* *name* can contain the data center value. In that case, dataCenter and clusterName are separated by single '$'
 character.

*REST Call:* POST http://localhost:25000/api/beacon/cluster/submit/primaryCluster

[source, properties]
fsEndpoint=hdfs://localhost:8020
beaconEndpoint=http://localhost:25000
hsEndpoint=http://localhost:10000
name=primaryCluster
description=primary cluster
user=ambari-qa
tags=consumer=consumer@xyz.com,owner=producer@xyz.com
dfs.namenode.kerberos.principal=hdfs/_HOST@YOUR-REALM.COM

*Response:*

[source, json]
{
   "requestId":"e5cc8230-f356-4566-9b65-536abdff8aa3",
   "message":"Submit successful (CLUSTER) primaryCluster",
   "status":"SUCCEEDED"
}

*Note:* dfs.namenode.kerberos.principal is custom property

GET api/beacon/cluster/list
---------------------------

*Description:* List cluster entities

*Parameters:*

* *_fields_* <optional> Entity output fields separated by commas. Valid options are peers and tags.
* *_orderBy_* <optional> Column by which results should be ordered. Sorted by descending order. Valid options are nominalTime (default) and status.
* *_sortOrder_* <optional> Valid options are “asc” and “desc”
* *_offset_* <optional> Show results from the offset. Used for pagination. Default is 0.
* *_numResults_* <optional> Number of instances per entity to show. Default value is 10.

*REST Call:* GET http://localhost:25000/api/beacon/cluster/list?fields=peers,tags

*Response:*

{
	"totalResults": 2,
	"results": 2,
	"cluster": [{
			"name": "backupCluster",
			"peers": ["primaryCluster"],
			"tags": ["consumer=consumer@xyz.com", "owner=producer@xyz.com"]
		},
		{
			"name": "primaryCluster",
			"peers": ["backupCluster"],
			"tags": ["consumer=consumer@xyz.com", "owner=producer@xyz.com"]
		}
	]
}

GET api/beacon/cluster/status/:cluster-name
-------------------------------------------

*Description:* Get status of the cluster

*Parameters:* _:cluster-name_ Name of the cluster

*REST Call:* GET http://localhost:25000/api/beacon/cluster/status/:cluster-name

*Response:*

* If request is successful:
[source, json]
{
  "name": "target",
  "status": "SUBMITTED"
}

* If request fails:
[source, json]
{
  "status": "FAILED",
  "message": "wrongCluster (CLUSTER) not found",
  "requestId": "876823802@qtp-1500379239-0"
}

GET api/beacon/cluster/getEntity/:cluster-name
----------------------------------------------

*Description:* Get cluster definition

*Parameters:* _:cluster-name_ Name of the cluster

*REST Call:* GET http://localhost:25000/api/beacon/cluster/getEntity/primaryCluster

*Response:*

[source, json]
{
   "name":"primaryCluster",
   "description":"primary",
   "fsEndpoint":"hdfs://localhost:8020",
   "hsEndpoint":"http://localhost:10000",
   "tags":"consumer=consumer@xyz.com,owner=producer@xyz.com",
   "peers":"c1, c2",
   "customProperties":{
      "dfs.namenode.kerberos.principal":"hdfs/_HOST@YOUR-REALM.COM"
   },
   "user":"ambari-qa",
   "entityType":"CLUSTER"
}

*Note:* peers:"c1, c2" is the list of remote clusters with which this cluster has been paired for replication purposes.

DELETE api/beacon/cluster/delete/:cluster-name
----------------------------------------------

*Description:* Delete cluster

*Parameters:* _:cluster-name_ Name of the cluster

*REST Call:* DELETE http://localhost:25000/api/beacon/cluster/delete/primaryCluster[__http://localhost:25000/api/beacon/cluster/delete/primaryCluster__]

*Response:*

_{_ +
_"requestId": "qtp2026718042-1933333",_ +
_"message": "primaryCluster(CLUSTER) removed successfully",_ +
_"status": "SUCCEEDED"_ +
_}_

POST api/beacon/policy/submit/:policy-name
------------------------------------------

*Description:* Submit an replication policy.

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25000/api/beacon/policy/submit/hivePolicy

[source, properties]
name=hivePolicy
type=HIVE
dataset=sales <Database to replicate>
sourceCluster=primaryCluster
targetCluster=backupCluster
frequencyInSec=3600
tags=owner=producer@xyz.com,component=sales
user=ambari-qa
retryAttempts=3
queue=default
maxEvents=-1

*Response:*

[source, json]
{
   "requestId":"qtp2026718042-19",
   "message":"Submit successful (REPLICATIONPOLICY) hivePolicy",
   "status":"SUCCEEDED"
}

*Note:* queue, maxEvents are custom properties

POST api/beacon/policy/schedule/:policy-name
--------------------------------------------

*Description:* Schedule submitted policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25000/api/beacon/policy/schedule/hivePolicy

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "hdfspolicy(REPLICATIONPOLICY) scheduled successfully",
  "requestId": "1223050066@qtp-1933129092-0"
}

POST api/beacon/policy/submitAndSchedule/:policy-name
-----------------------------------------------------

*Description:* Submit and schedule an replication policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25000/api/beacon/policy/submit/hivePolicy[__http://localhost:25000/api/beacon/policy/submitAndSchedule/hivePolicy__]

[source, properties]
name=hivePolicy
type=HIVE
dataset=sales <Database to replicate>
sourceCluster=primaryCluster
targetCluster=backupCluster
frequencyInSec=3600
tags=owner=producer@xyz.com,component=sales
user=ambari-qa
retryAttempts=3
queue=default
maxEvents=-1

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "Policy [hdfspolicy] submitAndSchedule successful",
  "requestId": "1917442783@qtp-1933129092-1"
}

*Note:* queue, maxEvents are custom properties

GET api/beacon/policy/list
--------------------------

*Description:* List replication policies.

*Parameters:* All the parameters are optional.

* *_fields:_* Entity output fields separated by commas. Valid options are status, tags, clusters, datasets, frequency, starttime and endtime.
* *_orderBy:_* Column by which results should be ordered. Valid options are name, status, type, sourcecluster, targetcluster, starttime, endtime and frequency.
* *_sortOrder:_* Valid options are 'asc' and 'desc'. Default is 'asc'.
* *_offset:_* Show results from the offset. Used for pagination. Default is 0.
* *_numResults:_* Number of instances per entity to show. Default value is 10.
* *_filterBy:_* Filter results by list of *field:value* pairs. Supported filter fields are name, status, type, sourcecluster and targetcluster.

*Example:* filterBy=sourcecluster:primaryCluster,targetcluster:backupCluster|thirdCluster

Query will do an *AND* among _filterBy_ fields. | within same filter field does an *OR*

*REST Call:* GET http://localhost:25000/api/beacon/policy/list?fields=status,tags,clusters,frequency,endtime,datasets

*Response:*

[source, json]
{
  "totalResults": 1,
  "results": 1,
  "policy": [
    {
      "type": "FS",
      "name": "hdfspolicy",
      "status": "SUBMITTED",
      "endTime": "9999-12-31T00:00:00",
      "sourceCluster": "source",
      "targetCluster": "target",
      "sourceDataset": "/tmp/test",
      "targetDataset": "/tmp/test",
      "frequencyInSec": 60,
      "tags": []
    }
  ]
}

GET api/beacon/policy/status/:policy-name
-----------------------------------------

*Description:* Get status of the policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* GET http://localhost:25000/api/beacon/policy/status/hivePolicy

*Response:*

* If request is successful:
[source, json]
{
  "name": "hivePolicy",
  "status": "RUNNING"
}

*Note:* Different status values for a policy: _SUBMITTED_, _RUNNING_, _SUSPENDED_.

* If request fails:
[source, json]
{
  "status": "FAILED",
  "message": "Policy does not exists name: hivePolicy",
  "requestId": "1223050066@qtp-1933129092-0"
}


GET api/beacon/policy/getEntity/:policy-name
--------------------------------------------

*Description:* Get policy definition

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* GET http://localhost:25000/api/beacon/policy/getEntity/hdfspolicy

*Response:*

[source, json]
{
  "policyId": "/source/source/hdfspolicy/0/1494218438617/000000001",
  "name": "hdfspolicy",
  "type": "FS",
  "status": "RUNNING",
  "lastInstanceStatus": "SUCCESS",
  "executionType": "FS",
  "sourceDataset": "/tmp/test",
  "targetDataset": "/tmp/test",
  "sourceCluster": "source",
  "targetCluster": "target",
  "startTime": null,
  "endTime": "9999-12-31T00:00:00",
  "frequencyInSec": 5,
  "tags": null,
  "customProperties": {
    "distcpMapBandwidth": "10",
    "targetSnapshotRetentionAgeLimit": "10",
    "sourceSnapshotRetentionNumber": "1",
    "distcpMaxMaps": "1",
    "preserveAcl": "false",
    "tdeEncryptionEnabled": "false",
    "preservePermission": "true",
    "targetSnapshotRetentionNumber": "1",
    "sourceSnapshotRetentionAgeLimit": "10"
  },
  "retry": {
    "attempts": 3,
    "delay": 1800
  },
  "user": "ambari-qa",
  "notification": {
    "type": null,
    "to": null
  },
  "entityType": "REPLICATIONPOLICY"
}

POST api/beacon/policy/suspend/:policy-name
-------------------------------------------

*Description:* Suspend a policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25000/api/beacon/policy/suspend/hdfspolicy

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "hdfspolicy(FS) suspended successfully",
  "requestId": "1223050066@qtp-1933129092-0"
}

POST api/beacon/policy/resume/:policy-name
------------------------------------------

*Description:* Resume a policy

*Parameters:* _:policy-name_ Name of the replication policy

*REST Call:* POST http://localhost:25000/api/beacon/policy/resume/hdfspolicy

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "hdfspolicy(FS) resumed successfully",
  "requestId": "1223050066@qtp-1933129092-0"
}

DELETE api/beacon/policy/delete/:policy-name
--------------------------------------------

*Description:* Delete policy

*Parameters:* _:policy-name_ Name of the policy

*REST Call:* DELETE http://localhost:25000/api/beacon/policy/delete/hdfsPolicy

*Response:*

[source, json]
{
  "status": "SUCCEEDED",
  "message": "hdfspolicy(FS) removed successfully.",
  "requestId": "1223050066@qtp-1933129092-0"
}

POST api/beacon/cluster/pair
----------------------------

*Description:* Pair the clusters

*Parameters:* _Remote cluster name_ +

*REST Call:* POST _http://localhost:25000/api/beacon/pair[http://localhost:25000/api/beacon/cluster/pair]?remoteClusterName=backupCluster_ +

*Response:*

_{_ +
_"requestId": "qtp2026718042-1933333",_ +
_"message": "Clusters successfully paired",_ +
_"status": "SUCCEEDED"_ +
_}_

POST api/beacon/cluster/unpair
------------------------------

*Description:* Unpair the clusters

*Parameters:* _Remote cluster name_

*REST Call:* POST _http://localhost:25000/api/beacon/pair[http://localhost:25000/api/beacon/cluster/unpair]?remoteClusterName=backupCluster_ +

*Response:*

_{_ +
_"requestId": "qtp2026718042-1933333",_ +
_"message": "Clusters successfully unpaired",_ +
_"status": "SUCCEEDED"_ +
_}_

GET api/beacon/policy/info/:policy-name
---------------------------------------

*Description:* Get type of the submitted replication policy

*Parameters:* :policy-name Name of the replication policy

*REST Call:* GET http://localhost:25000/api/beacon/policy/type/hdfsdr[http://localhost:25000/api/beacon/policy/info/hdfsdr]

*Response:*

_{_ +
_"requestId": "1549725679@qtp-1818544933-0",_ +
_"type": "FS"_ +
_}_

GET /api/beacon/policy/instance/list/:policy-name
-------------------------------------------------

*Description:* Get the list of policy instance. This does not allow listing the policy instance on source cluster.

*Parameters:* All the parameters are optional.

* *_filterBy:_* Each filter needs to be provided into a *key:value* pair format and different pairs will be separated by comma (,). The logical *AND* operation is used between all the provided filters.
* *_orderBy:_* default: startTime
* *_sortOrder:_* default: ASC
* *_offset:_* default: 0
* *_numResults:_* default: 10 and max: 1000

Supported *_filterBy_* fields are: *status*, *type*, *startTime*, *endTime*.

Date should be in the Beacon supported format i.e. : *yyyy-MM-dd'T'HH:mm:ss*.

Policy instance statuses are: *SUCCESS*, *FAILED*, *KILLED*.

*REST Call:* http://localhost:25000/api/beacon/policy/instance/list?filterBy=type:fs&numResults=1&sortOrder=DESC

*Response:*

[source, json]
{
  "totalResults": 1,
  "results": 1,
  "instance": [
    { +
      "id": "/source/source/hdfspolicy/0/1493974789815/000000001@1", +
      "policyId": "/source/source/hdfspolicy/0/1493974789815/000000001",
      "name": "hdfspolicy",
      "type": "FS",
      "executionType": "FS",
      "user": "abafna",
      "status": "SUCCESS",
      "trackingInfo": "job_1493727122960_0086",
      "startTime": "2017-05-05T08:59:53",
      "endTime": "2017-05-05T09:00:10",
      "message": "SUCCESS"
    }
  ]
}


GET /api/beacon/instance/list
-----------------------------

*Description:* Get the list of policy instance. When queried on a source cluster it will return empty list.

*Parameters:*

* *_filterBy:_* Each filter needs to be provided into a *key:value* pair format and different pairs need be separated by comma (,). The logical *AND* operation is used between all the provided filters.
* *_orderBy:_* default: startTime
* *_sortOrder:_* default: ASC
* *_offset:_* default: 0
* *_numResults:_* default: 10 and max: 1000

Supported *_filterBy_* fields are: *name*, *status*, *type*, *startTime*, *endTime*.

Date should be in the Beacon supported format i.e. : *yyyy-MM-dd'T'HH:mm:ss*.

Policy instance statuses are: *SUCCESS*, *FAILED*, *KILLED*.

*REST Call:* http://localhost:25000/api/beacon/instance/list?filterBy=type:fs&numResults=1&sortOrder=DESC

*Response:*

[source, json]
{
  "totalResults": 1,
  "results" : 1,
  "instance": [
    { +
      "id": "/source/source/hdfspolicy/0/1493974789815/000000001@1", +
      "policyId": "/source/source/hdfspolicy/0/1493974789815/000000001",
      "name": "hdfspolicy",
      "type": "FS",
      "executionType": "FS",
      "user": "abafna",
      "status": "SUCCESS",
      "trackingInfo": "job_1493727122960_0086",
      "startTime": "2017-05-05T08:59:53",
      "endTime": "2017-05-05T09:00:10",
      "message": "SUCCESS"
    }
  ]
}

POST /api/beacon/policy/instance/abort/:policy-name
---------------------------------------------------

*Description:* Abort a policy instance currently executing.

*Parameters:* :policy-name name of the policy whose running instance needs to be aborted.

*REST Call:* http://localhost:25000/api/beacon/policy/instance/abort/daily-user-policy

*Response:*

* When an instance of the policy is in execution.
[source, json]
{
  "status": "SUCCEEDED",
  "message": "policy instance abort status [true]",
  "requestId": "1223050066@qtp-1933129092-0"
}

* When no instance is in execution.
[source, json]
{
  "status": "SUCCEEDED",
  "message": "policy instance abort status [false]",
  "requestId": "1223050066@qtp-1933129092-0"
}

* When Policy is not in _RUNNING_ state. (_SUBMITTED_ or _SUSPENDED_ state)
[source, json]
{
  "status": "FAILED",
  "message": "Policy [daily-user-policy] is not in [RUNNING] state. Current status [SUBMITTED]",
  "requestId": "1223050066@qtp-1933129092-0"
}

GET api/beacon/events/policy/:policy_name
-----------------------------------------
*Description:* Get events based on policy name

*Parameters:*

* *_policy_name_*    :     Name of the policy
* *_start_*          :     start date from which events is to get (optional)
* *_end_*            :     end date upto which events is to get (optional)
* *_offset_*         :     Show results from offset. Used for pagination. Default is 0
* *_numResults_*     :     Number of events to show. Default value is 10

*REST call:* GET http://localhost:25000/api/beacon/events/policy/:policy_name

*Example:* http://locahost:25000/api/beacon/events/policy/hdfsdr

*Response:*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalCount": 3,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002@1",
      "event": "succeeded",
      "eventType": "policyinstance",
      "policyReplType": "FS",
      "severity": "info",
      "timestamp": "2017-05-16 08:59:00.491",
      "message": "policy instance succeeded"
    },
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
      "event": "scheduled",
      "eventType": "policy",
      "severity": "info",
      "timestamp": "2017-05-16 08:58:16.279",
      "message": "replication policy scheduled"
    },
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
      "event": "submitted",
      "eventType": "policy",
      "severity": "info",
      "timestamp": "2017-05-16 08:58:12.809",
      "message": "replication policy submitted"
    }
  ]
}

*Example:* http://sourcecluster:25000/api/beacon/events/policy/hdfsdr

Above rest call will return policy details from source cluster with flag

syncEvent=true, which signify that policy synced successfully on source cluster

after submission on target cluster.

[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "664969353@qtp-81722690-0",
  "totalCount": 1,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1495850268439/000000001",
      "event": "submitted",
      "eventType": "policy",
      "severity": "info",
      "syncEvent": true,
      "timestamp": "2017-05-27 01:57:49.838",
      "message": "replication policy submitted"
    }
  ]
}

GET api/beacon/events/:event_name
----------------------------------
*Description:* Get particular events on base of event_name

*Parameters:*

* *_event_name_*     :     Name of event
* *_eventEntityType_*:     Entity type for which events are required (optional)
* *_start_*          :     start date from which events is to get (optional)
* *_end_*            :     end date upto which events is to get (optional)
* *_offset_*         :     Show results from offset. Used for pagination. Default is 0
* *_numResults_*     :     Number of events to show. Default value is 10

*REST call:* GET http://localhost:25000/api/beacon/events/:event_name

*Example:* http://localhost:25000/api/beacon/events/submitted

*Response:*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalCount": 4,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
      "event": "submitted",
      "eventType": "policy",
      "severity": "info",
      "timestamp": "2017-05-16 08:58:12.809",
      "message": "replication policy submitted"
    },
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000001",
      "event": "submitted",
      "eventType": "policy",
      "severity": "info",
      "timestamp": "2017-05-16 08:43:48.917",
      "message": "replication policy submitted"
    },
    {
      "event": "submitted",
      "eventType": "cluster",
      "severity": "info",
      "timestamp": "2017-05-16 08:34:49.225",
      "message": "cluster entity submitted"
    },
    {
      "event": "submitted",
      "eventType": "cluster",
      "severity": "info",
      "timestamp": "2017-05-16 08:34:46.068",
      "message": "cluster entity submitted"
    }
  ]
}

GET http://localhost:25000/api/beacon/events/succeeded?eventEntityType=policyinstance
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalCount": 2,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002@84",
      "event": "succeeded",
      "eventType": "policyinstance",
      "policyReplType": "FS",
      "severity": "info",
      "timestamp": "2017-05-16 12:26:11.218",
      "message": "policy instance succeeded"
    },
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002@83",
      "event": "succeeded",
      "eventType": "policyinstance",
      "policyReplType": "FS",
      "severity": "info",
      "timestamp": "2017-05-16 12:23:41.438",
      "message": "policy instance succeeded"
    }
  ]
}


GET api/beacon/events/entity/:entity_type
-----------------------------------------

*Description:* Get events for entity type i.e system, cluster and policy

*Parameters:*

* *_entity_type_*     :     entity type can be system, cluster or policy
* *_start_*          :     start date from which events is to get (optional)
* *_end_*            :     end date upto which events is to get (optional)
* *_offset_*         :     Show results from offset. Used for pagination. Default is 0
* *_numResults_*     :     Number of events to show. Default value is 10


*REST call:* GET  http://localhost:25000/api/beacon/events/entity/system

*Response*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalCount": 2,
  "events": [
    {
      "policyId": "0.0.0.0",
      "event": "started",
      "eventType": "system",
      "severity": "info",
      "timestamp": "2017-05-16 14:10:54.369",
      "message": "beacon started successfully"
    },
    {
      "policyId": "0.0.0.0",
      "event": "stopped",
      "eventType": "system",
      "severity": "info",
      "timestamp": "2017-05-16 14:10:16.921",
      "message": "beacon stopped successfully"
    }
  ]
}

GET  http://localhost:25000/api/beacon/events/entity/cluster

GET http://localhost25000/api/beacon/events/entity/cluster?start=2017-03-16T00:00:00&end=2017-03-23T00:00:00&numResults=1&offset=1

GET http://localhost:25000/api/beacon/events/entity/policy?start=2017-05-16T00:00:00&end=2017-05-20T00:00:00&numResults=5&offset=1

GET http://localhost:25000/api/beacon/events/entity/policyinstance?start=2017-05-16T00:00:00&end=2017-05-20T00:00:00&numResults=15&offset=1


GET api/beacon/events/all
-------------------------
*Description:* Get all events in Beacon

*Parameters:*

* *_start_*          :     start date from which events is to get (optional)
* *_end_*            :     end date upto which events is to get (optional)
* *_sortOrder:_*     :     DESC|ASC (optional). Default is DESC.
* *_offset_*         :     Show results from offset. Used for pagination. Default is 0
* *_numResults_*     :     Number of events to show. Default value is 10

*REST call:* GET http://localhost:25000/api/beacon/events/all

*Response:*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalCount": 2,
  "events": [
    {
        "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
        "instanceId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002@101",
        "event": "succeeded",
        "eventType": "policyinstance",
        "policyReplType": "FS",
        "severity": "info",
        "timestamp": "2017-05-16 13:08:44.713",
        "message": "policy instance succeeded"
    },
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002@100",
      "event": "succeeded",
      "eventType": "policyinstance",
      "policyReplType": "FS",
      "severity": "info",
      "timestamp": "2017-05-16 13:06:06.011",
      "message": "policy instance succeeded"
    }
  ]
}

*Note:* By default output will have events sorted by timestamp in descending order.


GET api/beacon/events/instance
------------------------------

*Description:* Get particular policy instance id events

*Parameters:*

* *_instanceId_*     :     Instance Id for which events are required

*REST call:* GET http://localhost:25000/api/beacon/events/instance?instanceId=/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002@104

*Response:*
[source, json]
{
  "status": "SUCCEEDED",
  "message": "success",
  "requestId": "1198817209@qtp-1816468636-0",
  "totalCount": 1,
  "events": [
    {
      "policyId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002",
      "instanceId": "/beaconsource/beaconsource/hdfsdr/0/1494924228843/000000002@104",
      "event": "succeeded",
      "eventType": "policyinstance",
      "policyReplType": "FS",
      "severity": "info",
      "timestamp": "2017-05-16 13:16:06.614",
      "message": "policy instance succeeded"
    }
  ]
}

GET api/beacon/logs
-------------------
 *Description:* Get Beacon logs using filter field.

 *Parameters:*

 * *_filterBy:_* Filter needs to be provided into a *key:value* pair format.
 * *_start:_*  start date time from which logs need to obtain. (optional)
 * *_end:_*  end date time upto which logs need to obtain. (optional)
 * *_frequency:_* time period for which last hourly logs need to be looked for specified filter field, if start time is null. (default 12 hours)
 * *_numResults:_* number of logs messages required to be fetched. (default 100)

 Supported *_filterBy_* fields are: *user*, *cluster*, *policyname*, *policyid*, *instanceid*.

 DateTime should be in the Beacon supported format i.e. : *yyyy-MM-dd'T'HH:mm:ss*.

 *REST Call:* GET http://localhost:25000/api/beacon/logs?filterBy=user:ambari-qa

 *Response:*
 [source, json]
 {
   "status": "SUCCEEDED",
   "message": "2017-05-17 08:30:58,549 INFO  - [main:] ~ main-1 USER[ambari-qa] CLUSTER[beacontarget] App path: /home/ambari-qa/beacon-1.0.0.2.6.0.1-SNAPSHOT/server/webapp/beacon (Main:182)\n2017-05-17 08:30:58,551 INFO  - [main:] ~ main-1 USER[ambari-qa] CLUSTER[beacontarget] Beacon cluster: beacontarget (Main:182)\n",
   "requestId": "1844638642@qtp-948395645-2"
 }


 *REST Call:* http://localhost:25000/api/beacon/logs?filterBy=policyid:/beaconsource/beaconsource/hdfsdr/0/1495009895429/000000001&start=2017-05-15T00:00:00&end=2017-05-18T20:00:00&numResults=5

 *Response:*
 [source, json]
 {
   "status": "SUCCEEDED",
   "message": "2017-05-17 08:31:42,420 INFO  - [QuartzScheduler_Worker-1:] ~ QuartzScheduler_Worker-1-19 POLICYID[/beaconsource/beaconsource/hdfsdr/0/1495009895429/000000001] INSTANCEID[/beaconsource/beaconsource/hdfsdr/0/1495009895429/000000001@1] policy instance [/beaconsource/beaconsource/hdfsdr/0/1495009895429/000000001@1] to be executed. (QuartzJobListener:182)\n",
   "requestId": "1844638642@qtp-948395645-2"
 }