////
 HORTONWORKS DATAPLANE SERVICE AND ITS CONSTITUENT SERVICES

 (c) 2016-2018 Hortonworks, Inc. All rights reserved.

 This code is provided to you pursuant to your written agreement with Hortonworks, which may be the terms of the
 Affero General Public License version 3 (AGPLv3), or pursuant to a written agreement with a third party authorized
 to distribute this code.  If you do not have a written agreement with Hortonworks or with an authorized and
 properly licensed third party, you do not have any rights to this code.

 If this code is provided to you under the terms of the AGPLv3:
 (A) HORTONWORKS PROVIDES THIS CODE TO YOU WITHOUT WARRANTIES OF ANY KIND;
 (B) HORTONWORKS DISCLAIMS ANY AND ALL EXPRESS AND IMPLIED WARRANTIES WITH RESPECT TO THIS CODE, INCLUDING BUT NOT
    LIMITED TO IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE;
 (C) HORTONWORKS IS NOT LIABLE TO YOU, AND WILL NOT DEFEND, INDEMNIFY, OR HOLD YOU HARMLESS FOR ANY CLAIMS ARISING
    FROM OR RELATED TO THE CODE; AND
 (D) WITH RESPECT TO YOUR EXERCISE OF ANY RIGHTS GRANTED TO YOU FOR THE CODE, HORTONWORKS IS NOT LIABLE FOR ANY
    DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES INCLUDING, BUT NOT LIMITED TO,
    DAMAGES RELATED TO LOST REVENUE, LOST PROFITS, LOSS OF INCOME, LOSS OF BUSINESS ADVANTAGE OR UNAVAILABILITY,
    OR LOSS OR CORRUPTION OF DATA.
////

Beacon Getting Stated Guide
===========================

Building
--------

.Requirements
* maven
* java 1.7

.Building Beacon
----------------------------------------------
git clone https://github.com/hortonworks/beacon
cd beacon
mvn clean install
----------------------------------------------

.Create Beacon package
----------------------------------------------
mvn clean install -DskipTests
----------------------------------------------
The above command creates the package in distro/target with the following contents:

* bin
* conf
* docs
* hadooplibs
* server
** webapp
*** beacon.war
* sql

Local setup
-----------
In the package built above, the following command initialises the db schema and starts beacon server with local clustername as 'cluster-local' and at port 25000
----------------------------------------------
bin/beacon start
----------------------------------------------

To start multiple instances of beacon with mysql, make copies of beacon conf and set the following configurations:

* beacon.yml
----------------------------------------------
engine:
    ...
    port: <port>
    ...
dbStore:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://<mysql host>:3306/<beacondb>
----------------------------------------------

* beacon_env.ini
----------------------------------------------
...
BEACON_CLUSTER:<cluester name>
BEACON_LOG_DIR:logs/<cluster name>/
BEACON_PID_DIR:logs/<cluster name>/
...
----------------------------------------------

Now start beacon server with the above conf directory,
----------------------------------------------
export BEACON_CONF=<beacon conf directory> && bin/beacon start
----------------------------------------------

To enable debug mode to connect with IDE, set the following in beacon_env.ini
----------------------------------------------
BEACON_SERVER_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
----------------------------------------------

To stop beacon server,
----------------------------------------------
bin/beacon stop
----------------------------------------------






