= Beacon Hive Cloud Replication

Beacon supports hive replication from on prem cluster to cloud, it uses push based replication
where the replication job runs on the source on-prem cluster. Hive replication from cloud to on-prem is not supported.

Hive replication from on-prem to cloud requires the following:

* *Cluster setup*
** Source Cluster - On-prem cluster with data on HDFS. The cluster requires HDFS, YARN, Hiveserver2,
Ranger, Knox and Beacon services.
** Target Cluster - Datalake cluster on cloud with data on cloud storage. The cluster requires Hive Metastore,
Ranger, Knox and Beacon Services. Hive metastore should be configured with the following properties:
*** hive.metastore.warehouse.dir=<cloud storage>
*** hive.warehouse.subdir.inherit.perms=false
*** hive.repl.replica.functions.root.dir=<cloud storage>


* *Cluster Properties* for cluster submit API
** Source cluster - No changes
** Target cluster - The following minimum properties with the values from target cluster are required in target
cluster properties:
*** beaconEndpoint
*** hive.metastore.uris
*** hive.metastore.warehouse.dir
*** hive.warehouse.subdir.inherit.perms
*** hive.repl.replica.functions.root.dir
*** hive.metastore.kerberos.principal - for secure clusters

* *Replication Policy*
The replication policy has to be submitted on source cluster with the following minimal properties:
*** type=HIVE
*** sourceCluster
*** sourceDataset
*** targetCluster
*** cloudCred=<cloud credential entityid which contains credentials for cloud storage>
*** frequencyInSec
*** cloud.encryptionAlgorithm=<encryption algorithm for cloud object store>
*** cloud.encryptionKey=<encryption key for SSE-KMS algorithm>
